packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@types/node": ^24
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
  radix-ui: ^1.5.0
  uuid: ^14.0.0
  "@node-rs/argon2": ^2.0.2
  class-variance-authority: ^0.7.1
  "@tanstack/store": ^0.11.0
  "@tanstack/react-store": ^0.11.0
  "@alexanderhott/resultts": ^0.1.0
  lucide-react: ^0.577.0
  '@tanstack/react-table': latest
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
allowBuilds:
  "@parcel/watcher": true
  esbuild: true
