/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiFlagRouteImport } from './routes/api.flag'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard.index'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiOpenapiSplatRouteImport } from './routes/api.openapi.$'
import { Route as AppDashboardProjectNewRouteImport } from './routes/_app/dashboard.project.new'
import { Route as AppDashboardProjectProjectIdRouteImport } from './routes/_app/dashboard.project.$projectId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFlagRoute = ApiFlagRouteImport.update({
  id: '/api/flag',
  path: '/api/flag',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiSplatRoute = ApiOpenapiSplatRouteImport.update({
  id: '/api/openapi/$',
  path: '/api/openapi/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardProjectNewRoute = AppDashboardProjectNewRouteImport.update({
  id: '/dashboard/project/new',
  path: '/dashboard/project/new',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardProjectProjectIdRoute =
  AppDashboardProjectProjectIdRouteImport.update({
    id: '/dashboard/project/$projectId',
    path: '/dashboard/project/$projectId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/flag': typeof ApiFlagRoute
  '/api/openapi/$': typeof ApiOpenapiSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/dashboard/project/$projectId': typeof AppDashboardProjectProjectIdRoute
  '/dashboard/project/new': typeof AppDashboardProjectNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/flag': typeof ApiFlagRoute
  '/api/openapi/$': typeof ApiOpenapiSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/dashboard/project/$projectId': typeof AppDashboardProjectProjectIdRoute
  '/dashboard/project/new': typeof AppDashboardProjectNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/flag': typeof ApiFlagRoute
  '/api/openapi/$': typeof ApiOpenapiSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/dashboard/project/$projectId': typeof AppDashboardProjectProjectIdRoute
  '/_app/dashboard/project/new': typeof AppDashboardProjectNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/api/flag'
    | '/api/openapi/$'
    | '/api/rpc/$'
    | '/dashboard/'
    | '/dashboard/project/$projectId'
    | '/dashboard/project/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/api/flag'
    | '/api/openapi/$'
    | '/api/rpc/$'
    | '/dashboard'
    | '/dashboard/project/$projectId'
    | '/dashboard/project/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/api/flag'
    | '/api/openapi/$'
    | '/api/rpc/$'
    | '/_app/dashboard/'
    | '/_app/dashboard/project/$projectId'
    | '/_app/dashboard/project/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiFlagRoute: typeof ApiFlagRoute
  ApiOpenapiSplatRoute: typeof ApiOpenapiSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/flag': {
      id: '/api/flag'
      path: '/api/flag'
      fullPath: '/api/flag'
      preLoaderRoute: typeof ApiFlagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi/$': {
      id: '/api/openapi/$'
      path: '/api/openapi/$'
      fullPath: '/api/openapi/$'
      preLoaderRoute: typeof ApiOpenapiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard/project/new': {
      id: '/_app/dashboard/project/new'
      path: '/dashboard/project/new'
      fullPath: '/dashboard/project/new'
      preLoaderRoute: typeof AppDashboardProjectNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/project/$projectId': {
      id: '/_app/dashboard/project/$projectId'
      path: '/dashboard/project/$projectId'
      fullPath: '/dashboard/project/$projectId'
      preLoaderRoute: typeof AppDashboardProjectProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppDashboardProjectProjectIdRoute: typeof AppDashboardProjectProjectIdRoute
  AppDashboardProjectNewRoute: typeof AppDashboardProjectNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppDashboardProjectProjectIdRoute: AppDashboardProjectProjectIdRoute,
  AppDashboardProjectNewRoute: AppDashboardProjectNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiFlagRoute: ApiFlagRoute,
  ApiOpenapiSplatRoute: ApiOpenapiSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
